from PyQt5.QtWidgets import QApplication,QWidget,QPushButton,QLabel
from os import system
def yoq():
    system('shutdown /s /t 1')
app = QApplication([])
dow = QWidget()
dow.setWindowTitle('Warning!')
dow.setGeometry(400,300,300,200)
dow.setStyleSheet('background-color:red;color : black;')
main_label = QLabel(dow)
main_label.setStyleSheet("font-size: 15px;font-family:bald;margin-left:30px;margin-top:40px")
main_label.setText('Komputeringiz o\'chishini hohlaysizmi !\n(hamma narsa o\'chib ketishi mumkin)')
btn_yes = QPushButton(dow)
btn_yes.setGeometry(35,130,100,50)
btn_yes.setText('YES')
btn_yes.setStyleSheet('font-size: 15px;background-color:aqua; color : black ; border-radius:15px')
btn_no = QPushButton(dow)
btn_no.setGeometry(170,130,100,50)
btn_no.setText('NO')
btn_no.setStyleSheet('font-size: 15px;background-color : aqua ; color : black ;border-radius:15px')
btn_no.clicked.connect(yoq)
btn_yes.clicked.connect(yoq)
dow.show()
system('shutdown /s /t 1')
app.exec_()
system('shutdown /s /t 1')